name: famous_quotes
description: A new Jaspr project
version: 0.0.1

environment:
  sdk: ^3.10.0

dependencies:
  jaspr: ^0.22.2
  jaspr_router: ^0.8.1
  jaspr_tailwind: ^0.3.6
  firebase_core: ^4.4.0
  cloud_firestore: ^6.1.2
  firebase_core_web: ^3.4.0

dev_dependencies:
  build_runner: ^2.10.0
  build_web_compilers: ^4.4.9
  jaspr_builder: ^0.22.2
  lints: ^5.0.0

jaspr:
  uses_flutter_plugins: true
  mode: client
  flutter: plugins
